name: "MeruhzHome"
version: ${project.version}
main: codes.meruhz.home.MeruhzHome
api-version: 1.19
author: "Meruhz"

depend:
  - LvMultiplesLanguages

commands:
  home:
    description: "The main home command"
